import { Sparkles } from 'lucide-react';

import { Button } from '@/shared/components/ui/button';
import { Card } from '@/shared/components/ui/card';

type DailyBriefAction = {
  label: string;
  href: string;
};

type DailyBriefProps = {
  headline: string;
  supportingText: string;
  action?: DailyBriefAction | undefined;
};

// Product-specific — a small headline+supporting-text insight block, resolved deterministically
// by resolveTodayBrief (today-brief.ts), not generated by an LLM. Single current consumer
// (TodayPage); if Phase 3/4 (Progress, Active Context) end up needing the same
// eyebrow+headline+supporting-text shape, that's the point to evaluate extraction — not before
// (docs/design-system/FeatureImplementationRules.md "Third Use" rule).
//
// Sparkles + a flat accent color (never a gradient) is the "Go Plan synthesized this" visual
// anchor — deliberately not a robot/AI glyph, and deliberately not the brand gradient: Phase 2's
// Priority hero is meant to be the screen's one actionable hero, so Brief stays editorial/quiet.
export function DailyBrief({ headline, supportingText, action }: DailyBriefProps) {
  return (
    <Card className="gap-1 py-4">
      <div className="flex items-center gap-1.5 text-metadata font-semibold uppercase tracking-[0.08em] text-[var(--color-text-secondary)]">
        <Sparkles aria-hidden="true" className="size-3.5 text-[var(--color-accent)]" />
        Tóm tắt hôm nay
      </div>
      <p className="text-section-title text-[var(--color-text-primary)]">{headline}</p>
      <p className="text-body text-[var(--color-text-secondary)]">{supportingText}</p>
      {action ? (
        // Same Button-ghost-stripped-to-a-text-link override already established at
        // overview-widget-registry.wedding.tsx's ViewAllAction — reusing the exact recipe rather
        // than inventing a new one (docs/design-system/ExceptionsAndDebt.md, deferred TextAction
        // item: hand-roll consistently with the other 8+ instances, don't build the formal variant
        // off one more consumer).
        <Button
          className="mt-1 h-auto min-h-0 w-fit self-end gap-0 rounded-none p-0 text-sm font-medium text-[var(--color-brand-primary)] hover:bg-transparent hover:text-[color:color-mix(in_srgb,var(--color-brand-primary)_78%,black)]"
          href={action.href}
          variant="ghost"
        >
          {action.label} →
        </Button>
      ) : null}
    </Card>
  );
}
