import type {
  OverviewWidgetDefinition,
  PlanModuleDefinition,
  PlanModuleId,
} from '@/modules/plan/types/plan-modular';

const overviewWidgets: Record<string, OverviewWidgetDefinition> = {
  planSummary: { id: 'planSummary', moduleId: 'overview' },
  planningSnapshot: { id: 'planningSnapshot', moduleId: 'planning' },
  financeSummary: { id: 'financeSummary', moduleId: 'finance' },
  memberSummary: { id: 'memberSummary', moduleId: 'members' },
  weddingGuestSummary: { id: 'weddingGuestSummary', moduleId: 'weddingGuests' },
  travelItinerarySummary: { id: 'travelItinerarySummary', moduleId: 'travelItinerary' },
  debtSummary: { id: 'debtSummary', moduleId: 'debtTracking' },
};

export const planModuleRegistry: Record<PlanModuleId, PlanModuleDefinition> = {
  overview: {
    id: 'overview',
    defaultLabel: 'Tổng quan',
    navigation: { enabled: true },
    permissions: ['overview.view'],
    routes: [{ key: 'overview.home', pathname: '/plans/[planId]' }],
    overviewWidgets: [overviewWidgets.planSummary!],
  },
  planning: {
    id: 'planning',
    defaultLabel: 'Công việc',
    navigation: { enabled: true },
    permissions: ['planning.view', 'planning.createMilestone', 'planning.createTodo', 'planning.editTodo'],
    routes: [
      { key: 'planning.tab.milestones', pathname: '/plans/[planId]?tab=milestones' },
      { key: 'planning.tab.todos', pathname: '/plans/[planId]?tab=todos' },
    ],
    collections: [{ path: 'milestones' }, { path: 'todos' }],
    overviewWidgets: [overviewWidgets.planningSnapshot!],
  },
  finance: {
    id: 'finance',
    defaultLabel: 'Tài chính',
    navigation: { enabled: true },
    permissions: [
      'finance.view',
      'finance.createExpense',
      'finance.editOwnExpense',
      'finance.deleteOwnExpense',
      'finance.editAllExpense',
      'finance.deleteAllExpense',
      'finance.createIncome',
      'finance.editOwnIncome',
      'finance.deleteOwnIncome',
      'finance.manageSettlements',
    ],
    optionalDependencies: ['planning', 'members', 'travelItinerary', 'debtTracking'],
    routes: [
      { key: 'finance.tab.timeline', pathname: '/plans/[planId]?tab=timeline' },
      { key: 'finance.expense.new', pathname: '/plans/[planId]/expenses/new' },
      { key: 'finance.expense.detail', pathname: '/plans/[planId]/expenses/[expenseId]' },
      { key: 'finance.expense.edit', pathname: '/plans/[planId]/expenses/[expenseId]/edit' },
      { key: 'finance.income.detail', pathname: '/plans/[planId]/incomes/[incomeId]' },
      { key: 'finance.income.edit', pathname: '/plans/[planId]/incomes/[incomeId]/edit' },
    ],
    collections: [{ path: 'expenses' }, { path: 'incomes' }, { path: 'settlements' }],
    overviewWidgets: [overviewWidgets.financeSummary!],
  },
  members: {
    id: 'members',
    defaultLabel: 'Thành viên',
    navigation: { enabled: true },
    permissions: ['members.view', 'members.manage'],
    routes: [{ key: 'members.tab', pathname: '/plans/[planId]?tab=members' }],
    collections: [{ path: 'members' }, { path: 'invitations' }],
    overviewWidgets: [overviewWidgets.memberSummary!],
  },
  weddingGuests: {
    id: 'weddingGuests',
    defaultLabel: 'Khách mời',
    navigation: { enabled: true },
    permissions: ['weddingGuests.manageGuest'],
    routes: [{ key: 'weddingGuests.tab', pathname: '/plans/[planId]?tab=weddingGuests' }],
    collections: [
      { path: 'weddingGuests' },
      { path: 'weddingGuestGroups' },
      { path: 'guestInvitations' },
    ],
    overviewWidgets: [overviewWidgets.weddingGuestSummary!],
  },
  travelItinerary: {
    id: 'travelItinerary',
    defaultLabel: 'Lịch trình',
    navigation: { enabled: true },
    permissions: [
      'travelItinerary.view',
      'travelItinerary.createActivity',
      'travelItinerary.editActivity',
      'travelItinerary.deleteActivity',
    ],
    routes: [{ key: 'travelItinerary.tab', pathname: '/plans/[planId]?tab=travelItinerary' }],
    collections: [{ path: 'travelActivities' }],
    overviewWidgets: [overviewWidgets.travelItinerarySummary!],
  },
  debtTracking: {
    id: 'debtTracking',
    defaultLabel: 'Khoản vay',
    navigation: { enabled: true },
    permissions: ['debtTracking.view', 'debtTracking.createDebt', 'debtTracking.recordRepayment'],
    routes: [{ key: 'debtTracking.tab', pathname: '/plans/[planId]?tab=debtTracking' }],
    collections: [{ path: 'debts' }, { path: 'repayments' }],
    overviewWidgets: [overviewWidgets.debtSummary!],
  },
};
